import type { Item } from "./types";

// Demo inventory so the storefront works before the scanning app is connected.
// Kept in sync with storefront/supabase/seed.sql via `npm run seed:sql -w storefront`.
// Photos live in storefront/public/seed (the scanner proxies /seed/* to the storefront).

type SeedInput = Omit<
  Item,
  "id" | "status" | "receipt_id" | "created_at" | "updated_at" | "suggested_price_pence" | "photos" | "tags"
> & { photo: string; tags?: string[] };

const seed: SeedInput[] = [
  { sku: "OX-0101", title: "Faux fur coat", description: "Rich brown faux fur coat with wide lapels. Very warm and a real statement piece.", department: "womens", category: "coats-jackets", size_label: "14", size_alpha: "L", waist_in: null, colour: "brown", brand: "Hobbs", material: "Faux fur", condition: "excellent", price_pence: 2500, rack: "A1", photo: "faux-fur-coat", tags: ["warm", "winter", "vintage", "statement"] },
  { sku: "OX-0102", title: "Purple waterproof ski jacket", description: "Purple hooded ski-style jacket with contrast zips. Waterproof and very warm.", department: "womens", category: "coats-jackets", size_label: "M", size_alpha: "M", waist_in: null, colour: "purple", brand: "Columbia", material: "Polyester", condition: "excellent", price_pence: 1800, rack: "A1", photo: "purple-winter-coat", tags: ["warm", "winter", "waterproof", "hooded", "outdoor"] },
  { sku: "OX-0103", title: "Navy hooded rain parka", description: "Navy drawstring-waist raincoat with a striped hood lining. Packs down small.", department: "womens", category: "coats-jackets", size_label: "12", size_alpha: "M", waist_in: null, colour: "navy", brand: "Joules", material: "Cotton blend", condition: "good", price_pence: 1400, rack: "A1", photo: "navy-rain-parka", tags: ["rain", "waterproof", "spring", "hooded"] },
  { sku: "OX-0104", title: "Faux leather biker jacket", description: "Black faux leather biker jacket with asymmetric zip and zip pockets.", department: "womens", category: "coats-jackets", size_label: "10", size_alpha: "S", waist_in: null, colour: "black", brand: "River Island", material: "Faux leather", condition: "good", price_pence: 1500, rack: "A2", photo: "black-biker-jacket", tags: ["edgy", "going out", "layering"] },
  { sku: "OX-0105", title: "Tan leather biker jacket", description: "Soft real leather biker jacket in a warm tan, with quilted shoulders.", department: "mens", category: "coats-jackets", size_label: "M", size_alpha: "M", waist_in: null, colour: "brown", brand: "AllSaints", material: "Leather", condition: "good", price_pence: 2800, rack: "A2", photo: "tan-leather-jacket", tags: ["leather", "vintage", "classic"] },
  { sku: "OX-0106", title: "Cotton utility jacket", description: "Stone cotton utility jacket with button front and chest pockets.", department: "mens", category: "coats-jackets", size_label: "L", size_alpha: "L", waist_in: null, colour: "beige", brand: "Next", material: "Cotton", condition: "excellent", price_pence: 1600, rack: "A2", photo: "beige-field-jacket", tags: ["utility", "spring", "smart casual"] },
  { sku: "OX-0107", title: "Sherpa-collar denim jacket", description: "Light wash trucker jacket with a cosy borg collar and lining. Unisex fit.", department: "unisex", category: "coats-jackets", size_label: "M", size_alpha: "M", waist_in: null, colour: "blue", brand: "Levi's", material: "Denim", condition: "good", price_pence: 1200, rack: "A3", photo: "denim-jacket", tags: ["denim", "layering", "casual", "classic"] },
  { sku: "OX-0108", title: "Rust cable knit jumper", description: "Chunky cable knit jumper in a burnt orange-red.", department: "womens", category: "knitwear", size_label: "M", size_alpha: "M", waist_in: null, colour: "orange", brand: null, material: "Wool", condition: "excellent", price_pence: 800, rack: "B1", photo: "rust-cable-knit", tags: ["warm", "cosy", "handmade", "autumn"] },
  { sku: "OX-0109", title: "Chunky button-neck jumper", description: "Heavyweight grey knit with a buttoned funnel neck.", department: "unisex", category: "knitwear", size_label: "L", size_alpha: "L", waist_in: null, colour: "grey", brand: "Uniqlo", material: "Wool blend", condition: "good", price_pence: 900, rack: "B1", photo: "grey-chunky-knit", tags: ["warm", "cosy", "oversized", "winter"] },
  { sku: "OX-0110", title: "Oatmeal knit jumper", description: "Soft textured knit in oatmeal, relaxed fit.", department: "womens", category: "knitwear", size_label: "8", size_alpha: "S", waist_in: null, colour: "beige", brand: "M&S", material: "Lambswool blend", condition: "excellent", price_pence: 900, rack: "B1", photo: "oatmeal-knit", tags: ["warm", "cosy", "neutral"] },
  { sku: "OX-0111", title: "Cream roll-neck jumper", description: "Fine cream knit roll neck — a smart layering piece.", department: "womens", category: "knitwear", size_label: "M", size_alpha: "M", waist_in: null, colour: "white", brand: "& Other Stories", material: "Wool blend", condition: "excellent", price_pence: 1100, rack: "B2", photo: "white-rollneck", tags: ["warm", "cosy", "winter", "roll neck"] },
  { sku: "OX-0112", title: "Black crew-neck sweatshirt", description: "Plain heavyweight black crew-neck sweatshirt.", department: "mens", category: "tops", size_label: "M", size_alpha: "M", waist_in: null, colour: "black", brand: "COS", material: "Cotton", condition: "good", price_pence: 500, rack: "B2", photo: "black-sweatshirt", tags: ["basics", "casual", "everyday"] },
  { sku: "OX-0113", title: "Blue check shirt", description: "Blue and white check button-down shirt, long sleeves.", department: "mens", category: "shirts", size_label: "15.5\"", size_alpha: "M", waist_in: null, colour: "blue", brand: "Charles Tyrwhitt", material: "Cotton", condition: "excellent", price_pence: 600, rack: "B3", photo: "gingham-shirt", tags: ["smart", "office", "check"] },
  { sku: "OX-0114", title: "Red check flannel shirt", description: "Brushed cotton red and black buffalo check shirt — soft and warm.", department: "mens", category: "shirts", size_label: "L", size_alpha: "L", waist_in: null, colour: "red", brand: "Superdry", material: "Cotton flannel", condition: "good", price_pence: 700, rack: "B3", photo: "red-check-flannel", tags: ["warm", "check", "casual", "autumn"] },
  { sku: "OX-0115", title: "Hawaiian print shirt", description: "Short-sleeve camp-collar shirt with a blue hibiscus print.", department: "mens", category: "shirts", size_label: "M", size_alpha: "M", waist_in: null, colour: "blue", brand: "Topman", material: "Viscose", condition: "excellent", price_pence: 500, rack: "B3", photo: "hawaiian-shirt", tags: ["summer", "holiday", "print", "fun"] },
  { sku: "OX-0116", title: "Lilac slogan tee", description: "Lilac V-neck tee with an \"all we need\" heart print.", department: "womens", category: "t-shirts", size_label: "S", size_alpha: "S", waist_in: null, colour: "purple", brand: null, material: "Cotton", condition: "good", price_pence: 300, rack: "B4", photo: "be-kind-tee", tags: ["casual", "slogan", "summer"] },
  { sku: "OX-0117", title: "White ribbed long-sleeve top", description: "Fine white ribbed knit top with long sleeves.", department: "womens", category: "tops", size_label: "12", size_alpha: "M", waist_in: null, colour: "white", brand: "H&M", material: "Viscose jersey", condition: "excellent", price_pence: 300, rack: "B4", photo: "white-batwing-tee", tags: ["basics", "summer", "relaxed"] },
  { sku: "OX-0118", title: "Black floral maxi dress", description: "Black maxi dress with a pink rose print and sheer sleeves.", department: "womens", category: "dresses", size_label: "12", size_alpha: "M", waist_in: null, colour: "multi", brand: "Monsoon", material: "Polyester", condition: "excellent", price_pence: 1200, rack: "C1", photo: "floral-maxi-dress", tags: ["occasion", "wedding guest", "floral", "party"] },
  { sku: "OX-0119", title: "Black strapless maxi dress", description: "Strapless black maxi with a fitted bodice. Evening ready.", department: "womens", category: "dresses", size_label: "10", size_alpha: "S", waist_in: null, colour: "black", brand: "Karen Millen", material: "Crepe", condition: "new_with_tags", price_pence: 1500, rack: "C1", photo: "black-maxi-dress", tags: ["evening", "party", "occasion", "formal"] },
  { sku: "OX-0120", title: "Polka dot halter dress", description: "1950s-style white polka dot halter-neck dress.", department: "womens", category: "dresses", size_label: "8", size_alpha: "XS", waist_in: null, colour: "white", brand: "Hell Bunny", material: "Cotton", condition: "excellent", price_pence: 1800, rack: "C1", photo: "polka-prom-dress", tags: ["vintage", "retro", "party", "occasion"] },
  { sku: "OX-0121", title: "Sage tiered midi dress", description: "Sage green cotton midi dress with puff sleeves and a tiered skirt.", department: "womens", category: "dresses", size_label: "10", size_alpha: "S", waist_in: null, colour: "green", brand: "Whistles", material: "Linen blend", condition: "good", price_pence: 1000, rack: "C2", photo: "sage-midi-dress", tags: ["summer", "day", "linen"] },
  { sku: "OX-0122", title: "Mint tulle party dress", description: "Mint green tulle mini dress with puff sleeves.", department: "womens", category: "dresses", size_label: "8", size_alpha: "XS", waist_in: null, colour: "green", brand: "ASOS", material: "Polyester", condition: "excellent", price_pence: 800, rack: "C2", photo: "mint-tiered-dress", tags: ["party", "summer", "going out"] },
  { sku: "OX-0123", title: "Mid-wash straight jeans", description: "Classic straight-leg jeans in a light wash.", department: "womens", category: "jeans", size_label: "12 / W30 L30", size_alpha: "M", waist_in: 30, colour: "blue", brand: "Levi's", material: "Denim", condition: "good", price_pence: 1000, rack: "C3", photo: "light-wash-jeans", tags: ["denim", "everyday", "classic"] },
  { sku: "OX-0124", title: "Charcoal slim jeans", description: "Washed charcoal slim-fit jeans with a little stretch.", department: "mens", category: "jeans", size_label: "W32 L32", size_alpha: "M", waist_in: 32, colour: "grey", brand: "Jack & Jones", material: "Stretch denim", condition: "excellent", price_pence: 900, rack: "C3", photo: "dark-wash-jeans", tags: ["denim", "everyday", "slim"] },
  { sku: "OX-0125", title: "Black skinny jeans", description: "Washed black skinny jeans.", department: "mens", category: "jeans", size_label: "W30 L30", size_alpha: "S", waist_in: 30, colour: "black", brand: "Topman", material: "Stretch denim", condition: "good", price_pence: 800, rack: "C3", photo: "black-skinny-jeans", tags: ["denim", "skinny", "going out"] },
  { sku: "OX-0126", title: "Puma Future Rider trainers", description: "White and grey retro runners in suede and mesh. Barely worn.", department: "mens", category: "shoes", size_label: "UK 9", size_alpha: null, waist_in: null, colour: "white", brand: "Puma", material: "Suede / mesh", condition: "excellent", price_pence: 1500, rack: "D1", photo: "puma-trainers", tags: ["trainers", "retro", "casual", "sporty"] },
  { sku: "OX-0127", title: "White leather trainers", description: "Classic white leather low-tops.", department: "unisex", category: "shoes", size_label: "UK 8", size_alpha: null, waist_in: null, colour: "white", brand: "Nike", material: "Leather", condition: "good", price_pence: 1200, rack: "D1", photo: "white-trainers", tags: ["trainers", "everyday", "classic"] },
  { sku: "OX-0128", title: "Gold metallic court heels", description: "Pointed-toe court shoes in metallic gold.", department: "womens", category: "shoes", size_label: "UK 5", size_alpha: null, waist_in: null, colour: "gold", brand: "Kurt Geiger", material: "Faux leather", condition: "excellent", price_pence: 1400, rack: "D1", photo: "gold-court-heels", tags: ["heels", "party", "occasion", "wedding guest"] },
  { sku: "OX-0129", title: "Tan leather crossbody bag", description: "Real leather crossbody bag with adjustable strap and dog charm.", department: "womens", category: "bags", size_label: null, size_alpha: null, waist_in: null, colour: "brown", brand: "Radley", material: "Leather", condition: "good", price_pence: 1400, rack: "D2", photo: "tan-leather-bag", tags: ["leather", "everyday", "work"] },
  { sku: "OX-0130", title: "Black structured handbag", description: "Structured black handbag with long handles and a gold clasp.", department: "womens", category: "bags", size_label: null, size_alpha: null, waist_in: null, colour: "black", brand: "Dune", material: "Faux leather", condition: "excellent", price_pence: 1000, rack: "D2", photo: "black-handbag", tags: ["work", "smart", "everyday"] },
];

const BASE_DATE = Date.parse("2026-09-20T09:00:00Z");

export const SEED_ITEMS: Item[] = seed.map(({ photo, tags, ...rest }, i) => {
  const at = new Date(BASE_DATE - i * 37 * 60_000).toISOString();
  return {
    ...rest,
    id: `00000000-0000-4000-8000-${String(i + 1).padStart(12, "0")}`,
    photos: [`/seed/${photo}.jpg`],
    tags: tags ?? [],
    suggested_price_pence: rest.price_pence,
    status: "available",
    receipt_id: null,
    created_at: at,
    updated_at: at,
  };
});
