import type { Item } from "./types";

// Demo inventory so the storefront works before the scanning app is connected.
// Kept in sync with supabase/seed.sql via `npm run seed:sql`.

type SeedInput = Omit<
  Item,
  "id" | "status" | "receipt_id" | "created_at" | "updated_at" | "suggested_price_pence" | "photos" | "tags"
> & { photo: string; tags?: string[] };

const seed: SeedInput[] = [
  { sku: "OX-0101", title: "Faux fur collar coat", description: "Rich brown faux fur coat, fully lined with hook fastenings. Very warm and a real statement piece.", department: "womens", category: "coats-jackets", size_label: "14", size_alpha: "L", waist_in: null, colour: "brown", brand: "Hobbs", material: "Faux fur", condition: "excellent", price_pence: 2500, rack: "A1", photo: "faux-fur-coat", tags: ["warm", "winter", "vintage", "statement"] },
  { sku: "OX-0102", title: "3-in-1 waterproof winter coat", description: "Purple hooded ski-style coat with zip-out fleece lining. Waterproof and very warm.", department: "womens", category: "coats-jackets", size_label: "M", size_alpha: "M", waist_in: null, colour: "purple", brand: "Columbia", material: "Polyester", condition: "excellent", price_pence: 1800, rack: "A1", photo: "purple-winter-coat", tags: ["warm", "winter", "waterproof", "hooded", "outdoor"] },
  { sku: "OX-0103", title: "Navy hooded rain parka", description: "Lightweight drawstring-waist raincoat with striped lining. Packs down small.", department: "womens", category: "coats-jackets", size_label: "12", size_alpha: "M", waist_in: null, colour: "navy", brand: "Joules", material: "Cotton blend", condition: "good", price_pence: 1400, rack: "A1", photo: "navy-rain-parka", tags: ["rain", "waterproof", "spring", "hooded"] },
  { sku: "OX-0104", title: "Hooded faux leather biker jacket", description: "Black moto jacket with removable jersey hood and zip pockets.", department: "womens", category: "coats-jackets", size_label: "10", size_alpha: "S", waist_in: null, colour: "black", brand: "River Island", material: "Faux leather", condition: "good", price_pence: 1500, rack: "A2", photo: "black-biker-jacket", tags: ["edgy", "going out", "layering"] },
  { sku: "OX-0105", title: "Tan leather jacket", description: "Soft real leather jacket in a warm tan, lovely worn-in patina.", department: "mens", category: "coats-jackets", size_label: "M", size_alpha: "M", waist_in: null, colour: "brown", brand: "AllSaints", material: "Leather", condition: "good", price_pence: 2800, rack: "A2", photo: "tan-leather-jacket", tags: ["leather", "vintage", "classic"] },
  { sku: "OX-0106", title: "Cotton field jacket", description: "Stone cotton utility jacket with stand collar and four pockets.", department: "mens", category: "coats-jackets", size_label: "L", size_alpha: "L", waist_in: null, colour: "beige", brand: "Next", material: "Cotton", condition: "excellent", price_pence: 1600, rack: "A2", photo: "beige-field-jacket", tags: ["utility", "spring", "smart casual"] },
  { sku: "OX-0107", title: "Light wash denim jacket", description: "Classic trucker jacket with borg collar. Unisex fit.", department: "unisex", category: "coats-jackets", size_label: "M", size_alpha: "M", waist_in: null, colour: "blue", brand: "Levi's", material: "Denim", condition: "good", price_pence: 1200, rack: "A3", photo: "denim-jacket", tags: ["denim", "layering", "casual", "classic"] },
  { sku: "OX-0108", title: "Rust cable knit jumper", description: "Hand-knitted chunky cable jumper in a burnt orange wool.", department: "womens", category: "knitwear", size_label: "M", size_alpha: "M", waist_in: null, colour: "orange", brand: null, material: "Wool", condition: "excellent", price_pence: 800, rack: "B1", photo: "rust-cable-knit", tags: ["warm", "cosy", "handmade", "autumn"] },
  { sku: "OX-0109", title: "Chunky grey knit jumper", description: "Heavyweight ribbed knit, relaxed oversized fit.", department: "unisex", category: "knitwear", size_label: "L", size_alpha: "L", waist_in: null, colour: "grey", brand: "Uniqlo", material: "Wool blend", condition: "good", price_pence: 900, rack: "B1", photo: "grey-chunky-knit", tags: ["warm", "cosy", "oversized", "winter"] },
  { sku: "OX-0110", title: "Oatmeal knit jumper", description: "Soft brushed knit in oatmeal with ribbed cuffs.", department: "womens", category: "knitwear", size_label: "8", size_alpha: "S", waist_in: null, colour: "beige", brand: "M&S", material: "Lambswool blend", condition: "excellent", price_pence: 900, rack: "B1", photo: "oatmeal-knit", tags: ["warm", "cosy", "neutral"] },
  { sku: "OX-0111", title: "Oversized roll-neck jumper", description: "Cream chunky roll neck, long line — works as a jumper dress.", department: "womens", category: "knitwear", size_label: "M", size_alpha: "M", waist_in: null, colour: "white", brand: "& Other Stories", material: "Wool blend", condition: "excellent", price_pence: 1100, rack: "B2", photo: "white-rollneck", tags: ["warm", "cosy", "winter", "roll neck"] },
  { sku: "OX-0112", title: "Black crew sweatshirt", description: "Plain heavyweight black sweatshirt with tiny chest logo.", department: "mens", category: "tops", size_label: "M", size_alpha: "M", waist_in: null, colour: "black", brand: "COS", material: "Cotton", condition: "good", price_pence: 500, rack: "B2", photo: "black-sweatshirt", tags: ["basics", "casual", "everyday"] },
  { sku: "OX-0113", title: "Blue gingham shirt", description: "Crisp button-down gingham check shirt, long sleeves.", department: "mens", category: "shirts", size_label: "15.5\"", size_alpha: "M", waist_in: null, colour: "blue", brand: "Charles Tyrwhitt", material: "Cotton", condition: "excellent", price_pence: 600, rack: "B3", photo: "gingham-shirt", tags: ["smart", "office", "check"] },
  { sku: "OX-0114", title: "Red check flannel shirt", description: "Brushed cotton buffalo check shirt — soft and warm.", department: "mens", category: "shirts", size_label: "L", size_alpha: "L", waist_in: null, colour: "red", brand: "Superdry", material: "Cotton flannel", condition: "good", price_pence: 700, rack: "B3", photo: "red-check-flannel", tags: ["warm", "check", "casual", "autumn"] },
  { sku: "OX-0115", title: "Hawaiian print shirt", description: "Short-sleeve camp-collar shirt with blue hibiscus print.", department: "mens", category: "shirts", size_label: "M", size_alpha: "M", waist_in: null, colour: "blue", brand: "Topman", material: "Viscose", condition: "excellent", price_pence: 500, rack: "B3", photo: "hawaiian-shirt", tags: ["summer", "holiday", "print", "fun"] },
  { sku: "OX-0116", title: "\"Be Kind\" slogan tee", description: "Purple V-neck tee with knotted hem.", department: "womens", category: "t-shirts", size_label: "S", size_alpha: "S", waist_in: null, colour: "purple", brand: null, material: "Cotton", condition: "good", price_pence: 300, rack: "B4", photo: "be-kind-tee", tags: ["casual", "slogan", "summer"] },
  { sku: "OX-0117", title: "Draped batwing tee", description: "Soft white jersey top with batwing sleeves and ruched sides.", department: "womens", category: "t-shirts", size_label: "12", size_alpha: "M", waist_in: null, colour: "white", brand: "H&M", material: "Viscose jersey", condition: "excellent", price_pence: 300, rack: "B4", photo: "white-batwing-tee", tags: ["basics", "summer", "relaxed"] },
  { sku: "OX-0118", title: "Floral off-shoulder maxi dress", description: "Dark floral bardot maxi dress, fitted bodice and full skirt.", department: "womens", category: "dresses", size_label: "12", size_alpha: "M", waist_in: null, colour: "multi", brand: "Monsoon", material: "Polyester", condition: "excellent", price_pence: 1200, rack: "C1", photo: "floral-maxi-dress", tags: ["occasion", "wedding guest", "floral", "party"] },
  { sku: "OX-0119", title: "Black strapless maxi dress", description: "Strapless column maxi with pleated skirt. Evening ready.", department: "womens", category: "dresses", size_label: "10", size_alpha: "S", waist_in: null, colour: "black", brand: "Karen Millen", material: "Crepe", condition: "new_with_tags", price_pence: 1500, rack: "C1", photo: "black-maxi-dress", tags: ["evening", "party", "occasion", "formal"] },
  { sku: "OX-0120", title: "Polka dot prom dress", description: "1950s-style strapless dress with full skirt and bow detail.", department: "womens", category: "dresses", size_label: "8", size_alpha: "XS", waist_in: null, colour: "white", brand: "Hell Bunny", material: "Cotton", condition: "excellent", price_pence: 1800, rack: "C1", photo: "polka-prom-dress", tags: ["vintage", "retro", "party", "occasion"] },
  { sku: "OX-0121", title: "Sage button-through midi dress", description: "Sleeveless linen-look midi with button front and tie waist.", department: "womens", category: "dresses", size_label: "10", size_alpha: "S", waist_in: null, colour: "green", brand: "Whistles", material: "Linen blend", condition: "good", price_pence: 1000, rack: "C2", photo: "sage-midi-dress", tags: ["summer", "day", "linen"] },
  { sku: "OX-0122", title: "Mint tiered bandeau dress", description: "Strapless tiered mini dress with tie waist.", department: "womens", category: "dresses", size_label: "8", size_alpha: "XS", waist_in: null, colour: "green", brand: "ASOS", material: "Polyester", condition: "excellent", price_pence: 800, rack: "C2", photo: "mint-tiered-dress", tags: ["party", "summer", "going out"] },
  { sku: "OX-0123", title: "Mid-wash straight jeans", description: "Classic straight-leg jeans in a light-mid wash.", department: "womens", category: "jeans", size_label: "12 / W30 L30", size_alpha: "M", waist_in: 30, colour: "blue", brand: "Levi's", material: "Denim", condition: "good", price_pence: 1000, rack: "C3", photo: "light-wash-jeans", tags: ["denim", "everyday", "classic"] },
  { sku: "OX-0124", title: "Dark wash slim jeans", description: "Indigo slim-fit jeans with a little stretch.", department: "mens", category: "jeans", size_label: "W32 L32", size_alpha: "M", waist_in: 32, colour: "navy", brand: "Jack & Jones", material: "Stretch denim", condition: "excellent", price_pence: 900, rack: "C3", photo: "dark-wash-jeans", tags: ["denim", "everyday", "slim"] },
  { sku: "OX-0125", title: "Black skinny jeans", description: "Washed black skinny jeans with turn-up hem.", department: "mens", category: "jeans", size_label: "W30 L30", size_alpha: "S", waist_in: 30, colour: "black", brand: "Topman", material: "Stretch denim", condition: "good", price_pence: 800, rack: "C3", photo: "black-skinny-jeans", tags: ["denim", "skinny", "going out"] },
  { sku: "OX-0126", title: "Retro running trainers", description: "Colour-block suede and mesh runners. Barely worn.", department: "mens", category: "shoes", size_label: "UK 9", size_alpha: null, waist_in: null, colour: "multi", brand: "Puma", material: "Suede / mesh", condition: "excellent", price_pence: 1500, rack: "D1", photo: "puma-trainers", tags: ["trainers", "retro", "casual", "sporty"] },
  { sku: "OX-0127", title: "White leather trainers", description: "Clean white low-tops with red heel tab.", department: "unisex", category: "shoes", size_label: "UK 8", size_alpha: null, waist_in: null, colour: "white", brand: "Nike", material: "Leather", condition: "good", price_pence: 1200, rack: "D1", photo: "white-trainers", tags: ["trainers", "everyday", "classic"] },
  { sku: "OX-0128", title: "Gold metallic court heels", description: "Pointed-toe court shoes in metallic rose gold.", department: "womens", category: "shoes", size_label: "UK 5", size_alpha: null, waist_in: null, colour: "gold", brand: "Kurt Geiger", material: "Faux leather", condition: "excellent", price_pence: 1400, rack: "D1", photo: "gold-court-heels", tags: ["heels", "party", "occasion", "wedding guest"] },
  { sku: "OX-0129", title: "Tan leather shoulder bag", description: "Slouchy real leather shoulder bag with front zip pocket.", department: "womens", category: "bags", size_label: null, size_alpha: null, waist_in: null, colour: "brown", brand: "Radley", material: "Leather", condition: "good", price_pence: 1400, rack: "D2", photo: "tan-leather-bag", tags: ["leather", "everyday", "work"] },
  { sku: "OX-0130", title: "Black structured tote", description: "Smart black handbag with gold hardware and belt detail.", department: "womens", category: "bags", size_label: null, size_alpha: null, waist_in: null, colour: "black", brand: "Dune", material: "Faux leather", condition: "excellent", price_pence: 1000, rack: "D2", photo: "black-handbag", tags: ["work", "smart", "everyday"] },
];

const BASE_DATE = Date.parse("2026-09-20T09:00:00Z");

export const SEED_ITEMS: Item[] = seed.map(({ photo, tags, ...rest }, i) => {
  const at = new Date(BASE_DATE - i * 37 * 60_000).toISOString();
  return {
    ...rest,
    id: `00000000-0000-4000-8000-${String(i + 1).padStart(12, "0")}`,
    photos: [`/seed/${photo}.jpg`],
    tags: tags ?? [],
    suggested_price_pence: rest.price_pence,
    status: "available",
    receipt_id: null,
    created_at: at,
    updated_at: at,
  };
});
